#!/usr/bin/bash
# This code write by Mr.nope
if [[ "$id -u" -ne 0 ]]; then
  echo "
Please Run This Programm as Root!
"
  exit 1
fi
printf '\033]2;DDos-attack/Updating\a'
clear
echo "Updating DDos-Attack Tool..."
sleep 2
cd .. && cd .. && rm -r DDos-Attack && git clone https://github.com/mrprogrammer2938/DDos-Attack && cd DDos-Attack && bash install.sh
echo "
Updating..., Finish...!

"
exit 1
